### ISSUE TITLE
friends panel name alignment

### ISSUE THREAD

**Issue by ArceusOmkar7** [ArceusOmkar7/CodeNest-frontend#1]
**Describe the bug**
The names and images are not correctly aligned, distance b/w is close or more

**To Reproduce**
1. Open [index.html](https://github.com/ArceusOmkar7/CodeNest-frontend/blob/main/index.html)
2. Look at the friends panel on the left
3. See error

**Expected behavior**
Images and text should be aligned correctly

**Screenshots**
![image](https://github.com/ArceusOmkar7/CodeNest-frontend/assets/68581782/0bdc1a2c-1203-42ef-a79a-d90cb1b3536e)

**Comment by iamAayushMishra** [comment]
Made changes accordingly issue is resolved
